#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/icmc_visual_synth.jar:$APPDIR/lib/core.jar:$APPDIR/lib/opengl.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/video.jar:$APPDIR/lib/oscP5.jar:$APPDIR/lib/oscP5.jar" icmc_visual_synth
