/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeatureConfigurationMetaFrame.java
 *
 * Created on Dec 14, 2009, 12:17:25 AM
 */

package wekinator;

import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rebecca
 */
public class FeatureConfigurationMetaFrame extends javax.swing.JFrame {
    FeatureConfiguration fc = null;
    JCheckBox[] d1Boxes = null;
    JCheckBox[] d2Boxes = null;


    /** Creates new form FeatureConfigurationMetaFrame */
    public FeatureConfigurationMetaFrame() {
        initComponents();
    }

    public FeatureConfigurationMetaFrame(FeatureConfiguration fc) {
        initComponents();
        int numBase = fc.getNumBaseFeatures();

        JPanel test1 = new JPanel();
        test1.setLayout(new GridLayout(numBase, 2));
        d1Boxes = new JCheckBox[numBase];
        d2Boxes = new JCheckBox[numBase];
        String[] names = fc.getBaseFeatureNames();

        for (int i = 0; i < numBase; i++) {
            d1Boxes[i] = new JCheckBox("delta1", false);
        }
        for (int i = 0 ; i < numBase; i++) {
            d2Boxes[i] = new JCheckBox("delta2", false);
        }

        for (int i= 0; i < numBase; i++) {
            test1.add(new JLabel(names[i]));
            test1.add(d1Boxes[i]);
            test1.add(d2Boxes[i]);
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollFeaturePanel = new javax.swing.JScrollPane();
        panelFeatures = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelFeatures.setLayout(new javax.swing.BoxLayout(panelFeatures, javax.swing.BoxLayout.Y_AXIS));
        scrollFeaturePanel.setViewportView(panelFeatures);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollFeaturePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 239, Short.MAX_VALUE)
                .add(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(scrollFeaturePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addMetaFeatures();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    protected void addMetaFeatures() {
       // LinkedList<Integer>m //Problem: current method of doing things will break
        // if # of base features changes.... !
        //Need notion of Feature, MetaFeature.
        

    }

    private void addTestFeatures() {
           /* JPanel test1 = new JPanel();
            test1.setLayout(new BoxLayout(test1, BoxLayout.X_AXIS));
            test1.add(new JLabel("My name 1"));
            test1.add(new JCheckBox("d0"));
            test1.add(new JCheckBox("d1"));
            
                        JPanel test2 = new JPanel();
            test2.setLayout(new BoxLayout(test2, BoxLayout.X_AXIS));
            test2.add(new JLabel("My nameasdfadfadsf 1"));
            test2.add(new JCheckBox("d0"));
            test2.add(new JCheckBox("d1")); */
        JPanel test1 = new JPanel();
        test1.setLayout(new GridLayout(2, 3));
         test1.add(new JLabel("My name 1"));
            test1.add(new JCheckBox("d0"));
            test1.add(new JCheckBox("d1"));

             test1.add(new JLabel("My name 22"));
            test1.add(new JCheckBox("d0"));
            test1.add(new JCheckBox("d1"));
            

            panelFeatures.add(test1);
           // panelFeatures.add(test2);
            panelFeatures.repaint();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FeatureConfigurationMetaFrame f = new FeatureConfigurationMetaFrame();
               f.setVisible(true);
               f.addTestFeatures();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel panelFeatures;
    private javax.swing.JScrollPane scrollFeaturePanel;
    // End of variables declaration//GEN-END:variables

}
