/*
 * NewJFrame.java
 *
 * Created on January 24, 2009, 7:32 PM
 */
package wekinator;

/**
 *
 * @author  rebecca
 */
public class KnnSettingsFrame extends javax.swing.JFrame {

    protected IbkLearningAlgorithm learner;
    //  private IbkLearningAlgorithm backup;

    /**
     * Get the value of learner
     *
     * @return the value of learner
     */
    public IbkLearningAlgorithm getLearner() {
        return learner;
    }

    /**
     * Set the value of learner
     *
     * @param learner new value of learner
     */
    public void setLearner(IbkLearningAlgorithm learner) {
        //  this.backup = learner;
        this.learner = learner;
        if (learner != null) {
            textNumNeighbors.setText(Integer.toString(learner.getClassifier().getKNN()));
        }
    }

    /** Creates new form NewJFrame */
    public KnnSettingsFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textNumNeighbors = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("k-Nearest Neighbor Settings");

        jLabel2.setText("# Neighbors");

        textNumNeighbors.setText("10");
        textNumNeighbors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumNeighborsActionPerformed(evt);
            }
        });
        textNumNeighbors.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textNumNeighborsPropertyChange(evt);
            }
        });

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(buttonOK)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(buttonCancel))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(textNumNeighbors, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(textNumNeighbors, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonOK)
                    .add(buttonCancel))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
    int i = 1;
    try {
        i = Integer.parseInt(textNumNeighbors.getText());

    } catch (NumberFormatException ex) {
        i = 1;
    }
    if (i <= 0) {
        i = 1;
    }
    //   w.setNumNeighbors(i);
    learner.getClassifier().setKNN(i);
    this.dispose();

}//GEN-LAST:event_buttonOKActionPerformed

private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
    this.dispose();
}//GEN-LAST:event_buttonCancelActionPerformed

private void textNumNeighborsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumNeighborsActionPerformed
}//GEN-LAST:event_textNumNeighborsActionPerformed

private void textNumNeighborsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textNumNeighborsPropertyChange
}//GEN-LAST:event_textNumNeighborsPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textNumNeighbors;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {


                // ChuckConfigurationForm panel = new ChuckConfigurationForm(c);

                // panel.setVisible(true);
                KnnSettingsFrame frame = new KnnSettingsFrame();
                frame.setLearner(new IbkLearningAlgorithm());


                frame.setVisible(true);

                Console c = Console.getInstance();
                c.setVisible(true);
            }
        });
    }
}
