/*
 * NewJFrame.java
 *
 * Created on January 24, 2009, 7:32 PM
 */

package wekinator;

/**
 *
 * @author  rebecca
 */
public class SVMSettings extends javax.swing.JFrame {

    private WekaOperator w;
    
    /** Creates new form NewJFrame */
    public SVMSettings(WekaOperator w) {
        initComponents();
        this.w = w;
      //  int i = w.get //TODO
        
    }
    
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboKernel = new javax.swing.JComboBox();
        panelKernel = new javax.swing.JPanel();
        cardPolynomial = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textPolynomialExponent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkPolynomialUseLowerOrder = new javax.swing.JCheckBox();
        cardRBF = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        textRBFGamma = new javax.swing.JTextField();
        cardLinear = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("k-Nearest Neighbor Settings");

        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Complexity constant (C):");

        textC.setText("1");
        textC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCActionPerformed(evt);
            }
        });

        jLabel3.setText("Kernel:");

        comboKernel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linear", "Polynomial", "RBF" }));
        comboKernel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKernelActionPerformed(evt);
            }
        });

        panelKernel.setBorder(javax.swing.BorderFactory.createTitledBorder("Kernel Options"));
        panelKernel.setLayout(new java.awt.CardLayout());

        jLabel4.setText("Exponent");

        textPolynomialExponent.setText("2");
        textPolynomialExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPolynomialExponentActionPerformed(evt);
            }
        });

        jLabel5.setText("Use lower order terms");

        org.jdesktop.layout.GroupLayout cardPolynomialLayout = new org.jdesktop.layout.GroupLayout(cardPolynomial);
        cardPolynomial.setLayout(cardPolynomialLayout);
        cardPolynomialLayout.setHorizontalGroup(
            cardPolynomialLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardPolynomialLayout.createSequentialGroup()
                .addContainerGap()
                .add(cardPolynomialLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel5))
                .add(cardPolynomialLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cardPolynomialLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 169, Short.MAX_VALUE)
                        .add(textPolynomialExponent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(cardPolynomialLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(checkPolynomialUseLowerOrder)
                        .addContainerGap())))
        );
        cardPolynomialLayout.setVerticalGroup(
            cardPolynomialLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardPolynomialLayout.createSequentialGroup()
                .addContainerGap()
                .add(cardPolynomialLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textPolynomialExponent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cardPolynomialLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(checkPolynomialUseLowerOrder))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        panelKernel.add(cardPolynomial, "card2");

        jLabel6.setText("Gamma");

        textRBFGamma.setText("0.01");
        textRBFGamma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRBFGammaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout cardRBFLayout = new org.jdesktop.layout.GroupLayout(cardRBF);
        cardRBF.setLayout(cardRBFLayout);
        cardRBFLayout.setHorizontalGroup(
            cardRBFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardRBFLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 260, Short.MAX_VALUE)
                .add(textRBFGamma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cardRBFLayout.setVerticalGroup(
            cardRBFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardRBFLayout.createSequentialGroup()
                .addContainerGap()
                .add(cardRBFLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textRBFGamma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelKernel.add(cardRBF, "card2");

        jLabel8.setText("No options to set.");
        jLabel8.setEnabled(false);

        org.jdesktop.layout.GroupLayout cardLinearLayout = new org.jdesktop.layout.GroupLayout(cardLinear);
        cardLinear.setLayout(cardLinearLayout);
        cardLinearLayout.setHorizontalGroup(
            cardLinearLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardLinearLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        cardLinearLayout.setVerticalGroup(
            cardLinearLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(cardLinearLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel8)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        panelKernel.add(cardLinear, "card2");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelKernel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 130, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(comboKernel, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, textC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(buttonOK)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(textC, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(comboKernel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelKernel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonOK)
                    .add(buttonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
    System.out.println("This isn't implemented yet. TODO.");
    this.dispose();

}//GEN-LAST:event_buttonOKActionPerformed

private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
    this.dispose();
}//GEN-LAST:event_buttonCancelActionPerformed

private void textCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_textCActionPerformed

private void textPolynomialExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPolynomialExponentActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_textPolynomialExponentActionPerformed

private void textRBFGammaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRBFGammaActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_textRBFGammaActionPerformed

private void comboKernelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKernelActionPerformed
   setCard(comboKernel.getSelectedIndex());

}//GEN-LAST:event_comboKernelActionPerformed

public void setCard(int i) {
    cardLinear.setVisible(false);
    cardPolynomial.setVisible(false);
    cardRBF.setVisible(false);

    if (i == 0) {
     cardLinear.setVisible(true);
    } else if (i == 1) {
     cardPolynomial.setVisible(true);
    } else if (i == 2) {
        cardRBF.setVisible(true);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JPanel cardLinear;
    private javax.swing.JPanel cardPolynomial;
    private javax.swing.JPanel cardRBF;
    private javax.swing.JCheckBox checkPolynomialUseLowerOrder;
    private javax.swing.JComboBox comboKernel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelKernel;
    private javax.swing.JTextField textC;
    private javax.swing.JTextField textPolynomialExponent;
    private javax.swing.JTextField textRBFGamma;
    // End of variables declaration//GEN-END:variables

}
